apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: {{ .Values.amq.name }}
  name: {{ .Values.amq.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: {{ .Values.amq.name }}
  template:
    metadata:
      labels:
        application: {{ .Values.amq.name }}
        deployment: {{ .Values.amq.name }}
      name: {{ .Values.amq.name }}
    spec:
      containers:
        - env:
            - name: AMQ_USER
              value: {{ .Values.amq.user }}
            - name: AMQ_PASSWORD
              value: {{ .Values.amq.password }}
            - name: AMQ_ROLE
              value: admin
            - name: AMQ_NAME
              value: broker
            - name: AMQ_TRANSPORTS
              value: openwire,amqp,stomp,mqtt,hornetq
          image: {{ .Values.amq.image }}
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "/opt/amq/bin/readinessProbe.sh"
          name: {{ .Values.amq.name }}
          ports:
            - containerPort: 8161
              name: console-jolokia
              protocol: TCP
            - containerPort: 5672
              name: amqp
              protocol: TCP
            - containerPort: 1883
              name: mqtt
              protocol: TCP
            - containerPort: 61613
              name: stomp
              protocol: TCP
            - containerPort: 61616
              name: artemis
              protocol: TCP
      terminationGracePeriodSeconds: 60
