apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.amq.name }}
spec:
  lookupPolicy:
    local: true
  tags:
    - name: 'latest'
      from:
        kind: DockerImage
        name: {{ .Values.amq.image }}
