apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: broker
  template:
    metadata:
      labels:
        application: work-queue-broker
        deployment: broker
      name: broker
    spec:
      containers:
        - env:
            - name: AMQ_USER
              value: work-queue
            - name: AMQ_PASSWORD
              value: work-queue
            - name: AMQ_ROLE
              value: admin
            - name: AMQ_NAME
              value: broker
            - name: AMQ_TRANSPORTS
              value: openwire,amqp,stomp,mqtt,hornetq
          image: registry.access.redhat.com/amq-broker-7/amq-broker-72-openshift:1.3
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "/opt/amq/bin/readinessProbe.sh"
          name: broker
          ports:
            - containerPort: 8161
              name: console-jolokia
              protocol: TCP
            - containerPort: 5672
              name: amqp
              protocol: TCP
            - containerPort: 1883
              name: mqtt
              protocol: TCP
            - containerPort: 61613
              name: stomp
              protocol: TCP
            - containerPort: 61616
              name: artemis
              protocol: TCP
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The broker's console and Jolokia port.
  labels:
    application: broker
  name: "broker-jolokia"
spec:
  ports:
    - port: 8161
      targetPort: 8161
  selector:
    deployment: broker
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The broker's AMQP port.
  labels:
    application: broker
  name: "broker-amqp"
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    deployment: broker
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The broker's MQTT port.
  labels:
    application: broker
  name: "broker-mqtt"
spec:
  ports:
    - port: 1883
      targetPort: 1883
  selector:
    deployment: broker
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The broker's STOMP port.
  labels:
    application: broker
  name: "broker-stomp"
spec:
  ports:
    - port: 61613
      targetPort: 61613
  selector:
    deployment: broker
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The broker's OpenWire port.
  labels:
    application: broker
  name: "broker-tcp"
spec:
  ports:
    - port: 61616
      targetPort: 61616
  selector:
    deployment: broker
