frontend:
  name: spring-boot-messaging-work-queue-frontend
  version: 2.7-SNAPSHOT
  docker:
    image: quay.io/snowdrop/spring-boot-messaging-frontend-example:2.7
  env:
    - name: MESSAGING_SERVICE_HOST
      value: "broker-amqp"
    - name: MESSAGING_SERVICE_PORT
      value: "5672"
  s2i:
    env:
      - name: MAVEN_ARGS_APPEND
        value: "-pl frontend"
      - name: ARTIFACT_DIR
        value: "frontend/target"
worker:
  name: spring-boot-messaging-work-queue-worker
  version: 2.7-SNAPSHOT
  docker:
    image: quay.io/snowdrop/spring-boot-messaging-worker-example:2.7
  env:
    - name: MESSAGING_SERVICE_HOST
      value: "broker-amqp"
    - name: MESSAGING_SERVICE_PORT
      value: "5672"
  s2i:
    env:
      - name: MAVEN_ARGS_APPEND
        value: "-pl worker"
      - name: ARTIFACT_DIR
        value: "worker/target"
amq:
  name: broker
  image: registry.access.redhat.com/amq-broker-7/amq-broker-72-openshift:1.3
  port: 5672
  user: work-queue
  password: work-queue
